### ISSUE TITLE
ilp: find ilp implementation which we can embed

### ISSUE THREAD

**Issue by dj311** [dj311/uob-summer-project#1]
We need to figure out, in general
    how ilp will fit into this puzzle
and then,
    which ilp implementation best suits us.

For now I think this would be a good place to list all the implementations we've come across.

**Comment by dj311** [comment]
Metagol: 
  - Source code: https://github.com/metagol/metagol
  - Web interface: http://metagol.doc.ic.ac.uk/#
  - "Metagol is written in Prolog and runs with SWI-Prolog."

**Comment by dj311** [comment]
@xihajun I think I saw you using a prolog embedded in python yesterday. Do you have the link?

**Comment by dj311** [comment]
The ILP and neural network approaches (e.g. dILP) seem to _re-implement ILP_ rather than embed it as a layer. So if we go with that architecture, the question becomes: 
  - can we find an implementation of dILP/our architecture?
  - or how feasible is it to build our own?

**Comment by dj311** [comment]
@xihajun found this implementation of dILP on github https://github.com/ai-systems/DILP-Core/

**Comment by samanthawise** [comment]
Links for ILP methods:

https://www.biostat.wisc.edu/~page/ilp.pdf (theory)
https://www.cs.ox.ac.uk/activities/programinduction/Aleph/aleph.html (aleph manual - system used by Ray and Flach)

**Comment by dj311** [comment]
When using ILP in a continuous setting, one option would be to implement (an approximation of) ILP as layers embedded within a neural network. This seems doable, but would require a lot of people hours.

High-level:
  - The [SATNet](https://arxiv.org/pdf/1905.12149.pdf) project embeds a SAT solver as layers within a neural network.
  - Appendix B in the [dILP paper](https://arxiv.org/pdf/1711.04574.pdf) describes how they convert ILP into a satisfisability problem.
  - Needs more fleshing out.

**Comment by sydneyvert** [comment]
not doing combination method
