### ISSUE TITLE
ilp: research & think about appropriate meta-rules for ILP to use on a code property graph

### ISSUE THREAD

**Issue by dj311** [dj311/uob-summer-project#15]

**Comment by samanthawise** [comment]
- [Derivation reduction of metarules in meta-interpretive learning (http://andrewcropper.com/pubs/ilp18-dreduce.pdf)

- [Logical minimisation of meta-rules within Meta-Interpretive
Learning](http://andrewcropper.com/pubs/ilp14-minmeta.pdf)

**Comment by sydneyvert** [comment]
https://www.doc.ic.ac.uk/~shm/Papers/rulemlabs.pdf
^ Meta interpretive learning: achievements and challenges

**Comment by sydneyvert** [comment]
Nice, easy to follow slide show using some parts of the above paper. https://easychair.org/smart-program/LPAR-21/LPAR-21-s1-Muggleton.pdf

**Comment by sydneyvert** [comment]
Trees:
Horrible to read but quite helpful http://www.cis.upenn.edu/~xtag/meetings/msg00079.html
Potentially helpful with how to use graphs https://www.research.ed.ac.uk/portal/files/26605817/paper_02.pdf

**Comment by samanthawise** [comment]
[Was the Year 2000 a Leap Year? Step-Wise Narrowing Theories with Metagol](https://link.springer.com/content/pdf/10.1007%2F978-3-319-99960-9_9.pdf)

> Metagol is a two step approach. First, a candidate program is abduced by successively proving all positive examples. The number of clauses in the candidate program is limited. Second, Metagol verifies that no negative examples can be proven using this program. Prolog’s backtracking ensures that a solution is found if it exists. If no solution can be found within the given clause limit, it is step-by-step increased using an iterative deepening strategy. Thus, the smallest program (in number of clauses) will be found first. Figure 1 shows the Metagol algorithm in pseudo-code.

> In the first step, each example is proven either – using only background knowledge, – using clauses from the already induced program, or – by matching it against the head of one meta-rule, adding the resulting clause to the program, and proving the meta-rule body recursively. In the second step, Metagol verifies that no negative example can be proven using only background knowledge and already abduced clause, that is without changing the program. Technically, background knowledge is provided by indicating eligible predicate symbols and their arity. Clauses for these predicates, possibly including predefined predicates, are provided in the Prolog database. Meta-rules with their name and a list of variables to be existentially quantified are given as clauses with an appropriate head in the Prolog database. Positive and negative examples are presented as lists of positive ground atoms. Metagol assumes that all positive examples share the same predicate symbol and arity. However, this is not strictly required.

**Comment by samanthawise** [comment]
[Can predicate invention compensate for incomplete background knowledge?](http://andrewcropper.com/pubs/scai15-incomplete.pdf)

> To demonstrate this technique, suppose that the background knowledge consists of the single ground atom parent(alice,bob) and the single inverse metarule, and that our goal is the ground atom child(bob,alice). To prove this goal, a MIL learner fetches the inverse metarule and applies the meta-substitution θ = {P/child} to unify the head of the metarule with the goal. The unbound existential higher-order variable Q in the metarule is then bound to parent predicate symbol in the predicate signature to form the meta-substitution θ’ = {P/child,Q/parent}. The ground atom metasub(inverse,child,parent), representing the meta-substitution θ’, is saved in an abduction store, and the learner continues the proof by attempting to prove the body of the metarule. Once a proof is complete, the ground atom metasub(inverse,child,parent), saved in the abduction store, is projected onto the corresponding metarule to obtain the inductive hypothesis child(X,Y) ← parent(Y,X).

**Comment by xihajun** [comment]
Language template -> get clauses (top-down) metagol
Do we need to try Bottom-up ILP?  prolog

**Comment by xihajun** [comment]
> It seems that metagol cannot learn the cyclic task from a graph
<sub>[View in Slack](https://uobsummerproject.slack.com/archives/CHT1BNL9X/p1562278068000200)</sub>

**Comment by sydneyvert** [comment]
Not using Metagol.
