### ISSUE TITLE
Look at representing graph as a nxn adjacency matrix, with extra columns for features of each node.

### ISSUE THREAD

**Issue by sydneyvert** [dj311/uob-summer-project#29]

**Comment by xihajun** [comment]
The adjacency matrix data
https://drive.google.com/file/d/1mPVpAYO3tlt1BPjt_xNEGBynFhlPVBKp/view?usp=sharing

```
with open("../data/adj.pickle",'rb') as f:
    adj = pickle.load(f)
```

**Comment by dj311** [comment]
![2019-07-26-151258_1320x731_scrot](https://user-images.githubusercontent.com/5940946/61954027-c9208500-afaf-11e9-9d16-c9dbfa7e23ae.png)

We're making progress!

**Comment by dj311** [comment]
90% on second epoch! 
![2019-07-26-153047_1350x662_scrot](https://user-images.githubusercontent.com/5940946/61954983-0259f480-afb2-11e9-8271-4dafe0fce750.png)

**Comment by dj311** [comment]
untagged commit : https://github.com/dj311/uob-summer-project/commit/363c18150ac6684edfdf05bbbfd72256bd8c1e0b
