### ISSUE TITLE
ilp: add richer node properties e.g. is it a memory allocation, assignment etc?

### ISSUE THREAD

**Issue by sydneyvert** [dj311/uob-summer-project#31]

**Comment by dj311** [comment]
Potential properties:
  - Stuff from our handcrafted metagol: pointer, memory_allocation, size_of
  - Rules to help with more concise graph traversal, e.g.
    - `runs_before` using cfg
  - Add more edge types from the [code property graph](https://github.com/ShiftLeftSecurity/codepropertygraph/#overview), e.g.
    - reference edges

**Comment by sydneyvert** [comment]
New code with only +node on nodetypes at the top gives:

bug(A) :- writeToPointer(A).

**Comment by sydneyvert** [comment]
```
:- modeh(*, bug(+node))?

:- modeb(*, ast(+node,-node))?
:- modeb(*, ast(-node,+node))?

:- modeb(*, cfg(+node,-node))?
:- modeb(*, cfg(-node,+node))?

:- modeb(*, ref(+node,-node))?
:- modeb(*, ref(-node,+node))?

:- modeb(*, assignment(+node))?
:- modeb(*, compMemberAccess(+node))?
:- modeb(*, sizeOf(+node))?
:- modeb(*, malloc(+node))?
:- modeb(*, alloc(+node))?
:- modeb(*, writeToPointer(+node))?

%:- modeb(*, assignment(-node))?
%:- modeb(*, compMemberAccess(-node))?
%:- modeb(*, sizeOf(-node))?
%:- modeb(*, malloc(-node))?
%:- modeb(*, alloc(-node))?
%:- modeb(*, writeToPointer(-node))?```

**Comment by xihajun** [comment]
something wrong with good example 62852: id_126_f_memcpy_01_c_l_31_c_8_

**Comment by dj311** [comment]
More work:

`e180dd91` - ilp: document joern-ey into progol and try runs_before rule
`ab1609a7` - ilp: python module for rendering ilp rules as graphs
`326da9ec` - ilp: more description of whats been happening
`f60ccfb3` - add bad_node_label to git lfs
`91231a7c` - ilp: fix memcpy typo, add writeToPointer high-level rule + graphs
